name: kedro

on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  kedro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Kedro
      uses: WaylonWalker/kedro-action@2.0.0
      with:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }} # required for push to kedro-action branch
