name: MissPell

on:
  push:
  pull_request:

jobs:
  misspell:
    name: misspell based reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          level: info
          github_token: ${{ secrets.GITHUB_TOKEN }}
